"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {api} from "@/lib/api";

const next={RFQ:"QUOTED",QUOTED:"ORDERED",ORDERED:"SHIPPING",SHIPPING:"CLOSED"} as Record<string,string>;
const steps=["RFQ","QUOTED","ORDERED","SHIPPING","CLOSED"];

export default function ProjectPage(){
 const params=useParams(); const id=String(params.id);
 const [p,setP]=useState<any>(null),[comment,setComment]=useState(""),[draft,setDraft]=useState(""),[override,setOverride]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false);
 const [form,setForm]=useState<Record<string,string>>({});
 async function load(){try{const data=await api<any>(`/projects/${id}`);setP(data);const f=data.financials;setForm(Object.fromEntries(Object.entries(f).map(([k,v])=>[k,String(v??0)])))}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[id]);
 async function transition(){setBusy(true);setError("");try{await api(`/projects/${id}/transition`,{method:"POST",body:JSON.stringify({to_status:next[p.status],override_reason:override.trim()||null})});setOverride("");await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function addComment(){if(!comment.trim())return;try{await api(`/projects/${id}/activities`,{method:"POST",body:JSON.stringify({message:comment.trim()})});setComment("");await load()}catch(e:any){setError(e.message)}}
 async function saveFinancials(){setBusy(true);setError("");try{const role=JSON.parse(localStorage.getItem("mbm_user")||"{}").role;const fields=role==="ADMIN"?Object.keys(form):role==="SALES"?["estimated_revenue","actual_revenue","customer_balance_due"]:["estimated_supplier_cost","actual_supplier_cost","estimated_expenses","actual_expenses"];const body=Object.fromEntries(fields.map(k=>[k,Number(form[k]||0)]));await api(`/projects/${id}/financials`,{method:"PATCH",body:JSON.stringify(body)});setEditing(false);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function makeDraft(){setBusy(true);try{const r=await api<any>(`/ai/draft-followup/${id}`,{method:"POST"});setDraft(r.draft)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function confirmDraft(){try{await api(`/ai/confirm-draft/${id}`,{method:"POST",body:JSON.stringify({message:draft})});setDraft("");await load()}catch(e:any){setError(e.message)}}
 if(error&&!p)return <main className="container"><div className="card error">{error}</div></main>; if(!p)return <main className="container">Loading…</main>;
 const f=p.financials; const user=typeof window!=="undefined"?JSON.parse(localStorage.getItem("mbm_user")||"{}"):{role:""}; const role=user.role; const isAdmin=role==="ADMIN", canEdit=role==="ADMIN"||role==="SALES"||role==="PROCUREMENT"; const costVisible=role==="ADMIN"||role==="PROCUREMENT";
 return <main className="container stack">
  {error&&<div className="card error">{error}</div>}
  <div className="card stack">
   <div className="row between"><div><div className="small muted">{p.customer}</div><h1 style={{marginBottom:6}}>{p.project_name}</h1><div className="row"><span className="badge green">{p.status}</span><span className="small muted">Owner: {p.owner}</span><span className="small muted">Due: {p.due_date||"—"}</span></div></div>{next[p.status]&&<button className="btn" onClick={transition} disabled={busy}>{p.status==="SHIPPING"&&p.hold?"Attempt Close":"Move to "+next[p.status]}</button>}</div>
   {p.hold&&<div className="card attention"><strong>Shipment hold:</strong> customer balance {p.balance_due!=null ? `$${Number(p.balance_due).toLocaleString()} is outstanding.` : "is outstanding."} Closing is blocked until an Admin overrides the hold with a reason.{isAdmin&&<input className="input" placeholder="Admin override reason" value={override} onChange={e=>setOverride(e.target.value)} style={{marginTop:10}}/>}</div>}
   <div><strong>Next Action:</strong> {p.next_action||<span className="muted">None set</span>}</div>
  </div>
  <div className="card"><h2>Workflow</h2><div className="workflow">{steps.map((s,i)=>{const current=steps.indexOf(p.status);return <div key={s} className={i<=current?"workflow-step active":"workflow-step"}><span>{i+1}</span>{s}</div>})}</div></div>
  <section className="grid two">
   <div className="stack">
    <div className="card stack"><div className="row between"><h2>Financial Control</h2>{canEdit&&<button className="btn secondary" onClick={()=>setEditing(!editing)}>{editing?"Cancel":"Edit"}</button>}</div>
     {editing?<div className="grid two">{(isAdmin||role==="SALES")&&<><MoneyInput label="Estimated Revenue" k="estimated_revenue" form={form} setForm={setForm}/><MoneyInput label="Actual Revenue" k="actual_revenue" form={form} setForm={setForm}/><MoneyInput label="Customer Balance Due" k="customer_balance_due" form={form} setForm={setForm}/></>}{costVisible&&<><MoneyInput label="Estimated Supplier Cost" k="estimated_supplier_cost" form={form} setForm={setForm}/><MoneyInput label="Actual Supplier Cost" k="actual_supplier_cost" form={form} setForm={setForm}/><MoneyInput label="Estimated Expenses" k="estimated_expenses" form={form} setForm={setForm}/><MoneyInput label="Actual Expenses" k="actual_expenses" form={form} setForm={setForm}/></>}<button className="btn" onClick={saveFinancials} disabled={busy} style={{gridColumn:"1/-1"}}>Save financials</button></div>:<FinancialView f={f} role={role}/>} 
    </div>
    <div className="card stack"><h2>Activity Timeline</h2><div className="timeline">{p.activities.map((a:any)=><div className="activity" key={a.id}><strong>{a.activity_type}</strong><div style={{whiteSpace:"pre-wrap"}}>{a.message}</div><div className="small muted">{a.user_name||"System"} · {new Date(a.created_at).toLocaleString()}</div></div>)}</div><textarea className="input textarea" value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a project update…"/><button className="btn secondary" onClick={addComment}>Add update</button></div>
   </div>
   <div className="stack"><div className="card stack"><h2>Ask My Business</h2><p className="muted small">Database-grounded and role-filtered. AI only drafts; humans approve.</p><button className="btn" onClick={makeDraft} disabled={busy}>Draft Follow-up Email</button>{draft&&<><textarea className="input textarea" value={draft} onChange={e=>setDraft(e.target.value)}/><div className="row"><button className="btn" onClick={confirmDraft}>Edit & Confirm</button><button className="btn ghost" onClick={()=>setDraft("")}>Discard</button></div></>}</div><div className="card"><h2>Project Info</h2><div className="stack small"><div><span className="muted">Customer</span><br/>{p.customer}</div>{p.supplier&&<div><span className="muted">Supplier</span><br/>{p.supplier}</div>}<div><span className="muted">Last update</span><br/>{new Date(p.last_update).toLocaleString()}</div></div></div></div></section>
 </main>
}
function MoneyInput({label,k,form,setForm}:{label:string;k:string;form:Record<string,string>;setForm:React.Dispatch<React.SetStateAction<Record<string,string>>>}){return <label>{label}<input className="input" type="number" min="0" step="0.01" value={form[k]||"0"} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>}
function FinancialView({f,role}:{f:any;role:string}){const admin=role==="ADMIN", sales=role==="SALES";return <><div className="finance-table"><div></div><strong>Estimated</strong><strong>Actual</strong>{sales||admin?<><span>Revenue</span><span>${Number(f.estimated_revenue).toLocaleString()}</span><span>${Number(f.actual_revenue).toLocaleString()}</span></>:null}{!sales&&<><span>Supplier Cost</span><span>${Number(f.estimated_supplier_cost).toLocaleString()}</span><span>${Number(f.actual_supplier_cost).toLocaleString()}</span><span>Expenses</span><span>${Number(f.estimated_expenses).toLocaleString()}</span><span>${Number(f.actual_expenses).toLocaleString()}</span></>}{admin&&<><span>Total Cost</span><span>${(Number(f.estimated_supplier_cost)+Number(f.estimated_expenses)).toLocaleString()}</span><span>${Number(f.actual_total_cost).toLocaleString()}</span><span>Profit</span><span>—</span><span>${Number(f.profit).toLocaleString()}</span><span>Margin</span><span>—</span><span>{Number(f.margin_percent).toFixed(1)}%</span></>}{(sales||admin)&&<><span>Customer Balance Due</span><span>—</span><span>${Number(f.customer_balance_due).toLocaleString()}</span></>}</div>{!sales&&!admin&&<p className="small muted">Profit and margin are restricted to Admin.</p>}{sales&&<p className="small muted">Supplier costs and profit margin are restricted by role.</p>}</>}
