"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api} from "@/lib/api";

export default function Projects(){
  const [projects,setProjects]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[show,setShow]=useState(false),[name,setName]=useState(""),[customer,setCustomer]=useState(""),[owner,setOwner]=useState(""),[due,setDue]=useState(""),[action,setAction]=useState(""),[error,setError]=useState("");
  async function load(){try{const [p,c,u]=await Promise.all([api<any[]>("/projects"),api<any[]>("/customers"),api<any[]>("/users")]);setProjects(p);setCustomers(c);setUsers(u);if(!customer&&c[0])setCustomer(String(c[0].id));if(!owner&&u[0])setOwner(String(u[0].id))}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function create(e:React.FormEvent){e.preventDefault();setError("");try{await api("/projects",{method:"POST",body:JSON.stringify({project_name:name,customer_id:Number(customer),owner_id:Number(owner),due_date:due||null,next_action:action||null,financials:{}})});setName("");setDue("");setAction("");setShow(false);await load()}catch(e:any){setError(e.message)}}
  return <main className="container stack"><div className="row between"><div><h1>Projects</h1><p className="muted">Complete lifecycle from RFQ to Closed.</p></div><button className="btn btn-lg" onClick={()=>setShow(!show)}>{show?"Close form":"New RFQ"}</button></div>{error&&<div className="card error-panel"><strong>Projects could not be loaded.</strong><p>{error}</p><p className="small muted">For a fresh test, reset the PostgreSQL volume and run <code>python seed.py --reset</code>.</p></div>}{show&&<form className="card grid two" onSubmit={create}><label>Project name<input className="input" value={name} onChange={e=>setName(e.target.value)} required/></label><label>Customer<select className="input" value={customer} onChange={e=>setCustomer(e.target.value)}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Owner<select className="input" value={owner} onChange={e=>setOwner(e.target.value)}>{users.map(u=><option key={u.id} value={u.id}>{u.name} ({u.role})</option>)}</select></label><label>Due date<input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label style={{gridColumn:"1/-1"}}>Next action<input className="input" value={action} onChange={e=>setAction(e.target.value)} placeholder="e.g. Confirm technical scope"/></label><div><button className="btn">Create RFQ</button></div></form>}<div className="card table-card"><table className="table"><thead><tr><th>Project</th><th>Customer</th><th>Status</th><th>Owner</th><th>Due</th><th>Margin</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><Link className="link" href={`/projects/${p.id}`}>{p.project_name}</Link></td><td>{p.customer}</td><td><span className="badge">{p.status}</span></td><td>{p.owner}</td><td>{p.due_date||"—"}</td><td>{p.margin_percent?`${Number(p.margin_percent).toFixed(1)}%`:"—"}</td></tr>)}</tbody></table></div></main>
}
